import type {Knowledge} from './bots';
export const templates = [
 {slug:'juniper-cafe',name:'Juniper Café',category:'Café & bakery',icon:'☕',color:'#8b4b31',accent:'#fff0dd',tagline:'A little pause. A really good coffee.',description:'A neighborhood café for slow mornings, fresh bakes, and familiar faces.',intro:'Small-batch coffee, baked every morning.',services:[['House espresso','$3.50','A balanced double shot with chocolate notes.'],['Oat milk latte','$5.00','Our house espresso with silky oat milk.'],['Butter croissant','$4.00','Flaky, golden, and baked fresh each morning.']],hours:'Juniper Café is open Monday–Friday, 7am–6pm, and Saturday–Sunday, 8am–4pm.',contact:'Email hello@juniper.example for questions or catering requests.',location:'12 Maple Lane, Example Town',faq:[['Do you have dairy-free options?','Yes. Oat and almond milk are available, along with a rotating selection of vegan bakes.'],['Do I need a reservation?','No reservations are needed. Seating is first come, first served.'],['Do you offer catering?','Yes. We offer coffee and pastry catering for groups of 10–40. Please email hello@juniper.example at least 48 hours ahead.']],rules:[{id:'cafe-hours',trigger:'opening hours',reply:'We’re open Monday–Friday, 7am–6pm, and weekends, 8am–4pm. See you for coffee!'},{id:'cafe-menu',trigger:'menu',reply:'Our favorites: house espresso $3.50, oat milk latte $5, and butter croissant $4.'}]},
 {slug:'bright-dental',name:'Bright Dental',category:'Dental clinic',icon:'✦',color:'#23629a',accent:'#edf5ff',tagline:'A brighter smile starts with feeling at ease.',description:'Friendly, clear dental care for the whole family in a calm, welcoming space.',intro:'Thoughtful care, from your first visit.',services:[['Routine checkup','From $80','An examination and a conversation about your dental care.'],['Professional cleaning','From $100','A cleaning appointment tailored to your needs.'],['Whitening consultation','From $40','Discuss available options with the dental team.']],hours:'Bright Dental is open Monday–Friday, 8am–5pm. Saturday appointments are available from 9am–1pm. Closed Sunday.',contact:'Email appointments@brightdental.example to request an appointment. Requests are confirmed by the clinic.',location:'48 Willow Avenue, Example Town',faq:[['Are you accepting new patients?','Yes. New patients are welcome. Email appointments@brightdental.example to request your first appointment.'],['Do you accept insurance?','We accept selected insurance plans. Contact the clinic to confirm your specific plan before your visit.'],['What should I bring?','Please bring a photo ID, your insurance information if applicable, and a list of current medications.']],rules:[{id:'dental-book',trigger:'book appointment',reply:'Please email appointments@brightdental.example with your preferred date. Our team will confirm availability.'},{id:'dental-hours',trigger:'opening hours',reply:'Monday–Friday: 8am–5pm. Saturday: 9am–1pm by appointment. Closed Sunday.'}]},
 {slug:'fixwell-services',name:'Fixwell Home Services',category:'Home services',icon:'⌂',color:'#315538',accent:'#f0f5e8',tagline:'Good hands for the place you call home.',description:'Reliable help with everyday repairs, upkeep, and the jobs you never quite get around to.',intro:'One trusted team. A happier home.',services:[['General repairs','From $65 / hour','Doors, shelves, fixtures, and everyday household fixes.'],['Plumbing repairs','From $90 / visit','Help with dripping taps, blocked drains, and minor leaks.'],['Home maintenance','From $120 / visit','Seasonal checks and preventive maintenance.']],hours:'Fixwell Home Services operates Monday–Saturday, 8am–6pm. Closed Sunday. Emergency services are not available.',contact:'Email bookings@fixwell.example with your address and a description of the job to request a quote.',location:'Serving Example Town and nearby neighborhoods within 20 km.',faq:[['How do I get a quote?','Email bookings@fixwell.example with a description and photos of the job. We usually reply within one business day.'],['Where do you work?','We serve Example Town and neighborhoods within 20 km of the town center.'],['Is there a callout fee?','The standard callout fee is $30. It is credited toward the work if you accept the quote.']],rules:[{id:'fixwell-quote',trigger:'get a quote',reply:'Email bookings@fixwell.example with your address, job details, and a photo. We’ll reply within one business day.'},{id:'fixwell-emergency',trigger:'emergency',reply:'We don’t offer emergency callouts. For immediate danger, contact the appropriate local emergency service.'}]}
];
export function templateKnowledge(slug:string):Knowledge|undefined{
 const t=templates.find(t=>t.slug===slug);if(!t)return;
 return {sources:[{id:slug+'-website',title:t.name+' — example website',content:[t.name,t.description,t.hours,t.contact,t.location,...t.services.map(s=>s.join(': ')),...t.faq.map(f=>f.join('\n'))].join('\n\n')}],rules:t.rules};
}
