import Link from 'next/link';
import {notFound} from 'next/navigation';
import {templates, templateKnowledge} from '@/lib/templates';
import {TemplateChat} from './template-chat';
export default async function Template({params,searchParams}:{params:Promise<{slug:string}>;searchParams:Promise<{business?:string}>}){
 const {slug}=await params;const t=templates.find(x=>x.slug===slug);if(!t)notFound();
 const {business:businessId}=await searchParams;const backHref=businessId?'/?business='+encodeURIComponent(businessId):'/demos';
 return <main className="demo-site" style={{'--demo':t.color,'--demo-accent':t.accent} as React.CSSProperties}><div className="demo-banner">FICTIONAL DEMO WEBSITE <span>{businessId?'Testing your latest trained bot.':'All details and prices are examples.'}</span><a href={backHref} target="_top">Back to BotFoundry ↗</a></div><nav className="demo-nav"><Link href={'/templates/'+t.slug+(businessId?'?business='+encodeURIComponent(businessId):'')}>{t.icon} {t.name}</Link><div><a href="#services">{t.slug==='juniper-cafe'?'Menu':'Services'}</a><a href="#questions">FAQs</a><a href="#visit">Contact</a></div></nav><section className="demo-hero"><span className="eyebrow">{t.category} · EXAMPLE TOWN</span><h1>{t.tagline}</h1><p>{t.description}</p><a className="demo-button" href="#services">{t.slug==='juniper-cafe'?'Explore our menu':'Explore our services'} ↗</a><div className="demo-wordmark" aria-hidden="true">{t.slug==='juniper-cafe'?'BREW. BAKE. REPEAT.':t.slug==='bright-dental'?'CARE COMES FIRST.':'WE’LL TAKE CARE OF IT.'}</div></section><section className="demo-section" id="services"><span className="eyebrow">WHAT WE DO</span><h2>{t.intro}</h2><div className="demo-services">{t.services.map((s,i)=><article key={s[0]}><span>0{i+1}</span><h3>{s[0]}</h3><p>{s[2]}</p><strong>{s[1]}</strong></article>)}</div></section><section className="demo-details" id="visit"><div><span className="eyebrow">COME SAY HELLO</span><h2>A good place to start.</h2><p>{t.location}</p></div><div><h3>Opening hours</h3><p>{t.hours}</p><h3>Get in touch</h3><p>{t.contact}</p><small>Demo contact details do not receive messages.</small></div></section><section className="demo-section" id="questions"><span className="eyebrow">GOOD TO KNOW</span><h2>A few common questions.</h2>{t.faq.map(f=><article className="demo-faq" key={f[0]}><h3>{f[0]}</h3><p>{f[1]}</p></article>)}</section><footer className="demo-footer"><strong>{t.name}</strong><span>A fictional business template by BotFoundry.</span><a href={backHref} target="_top">Back to BotFoundry ↗</a></footer><TemplateChat businessName={t.name} knowledge={templateKnowledge(t.slug)!} businessId={businessId}/></main>;
}
